### ISSUE TITLE
create_user errors?????

### ISSUE THREAD

**Issue by dowelc** [CSE403FindersKeepers/finders-keepers#32]
Just tried to log in with a new account in the emulator and the server produced this stack trace and then died:

C:\Users\Generic Person\Desktop\CSE 403\finders-keepers>python server/run_server.py
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 304-350-115
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Nov/2016 14:36:13] "POST /api/create_user HTTP/1.1" 200 -
127.0.0.1 - - [28/Nov/2016 14:36:14] "GET /api/get_user/183 HTTP/1.1" 200 -
127.0.0.1 - - [28/Nov/2016 14:44:34] "POST /api/create_user HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Generic Person\Desktop\CSE 403\finders-keepers\server\server\__init__.py", line 262, in create_user
    return user_handler.create_user(json)
  File "C:\Users\Generic Person\Desktop\CSE 403\finders-keepers\server\server\handlers\user_handler.py", line 54, in create_user
    self.db_handler.cursor.execute("INSERT INTO USER VALUES(default,'','http://i.imgur.com/0bGFP47.jpg',0,'" + json["email"] + "', '')")
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\connections.py", line 835, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\connections.py", line 1019, in _read_query_result
    result.read()
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\connections.py", line 1302, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\connections.py", line 961, in _read_packet
    packet_header = self._read_bytes(4)
  File "C:\Users\Generic Person\Anaconda2\lib\site-packages\pymysql\connections.py", line 995, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 10054] An existing connection was forcibly closed by the remote host)')
127.0.0.1 - - [28/Nov/2016 14:44:34] "GET /api/get_user/-1 HTTP/1.1" 404 -

Then I closed the app and restarted the server and logged in with the same account on the same device just fine.

**Comment by dowelc** [comment]
It also triggered the same SQL error in a later get_trade request

**Comment by dowelc** [comment]
The FE doesn't handle errors at all

**Comment by dowelc** [comment]
Just checked in a potential fix. I got rid of the fetchalls after the inital fetchones in the queries for one thing by id (create_user, get_trade, get_item) there are still some left (get_user) so let's see there's a difference in where the errors pop up
